In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv("matches.csv")
df.head(5)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [69]:
df.shape

(1095, 20)

In [70]:
df.duplicated().sum()

np.int64(0)

In [71]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, season, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2]
Index: []

In [72]:
df = df.drop(columns=[
    'id',
    'season',
    'match_type',
    'super_over',
    'method',
    'umpire1',
    'umpire2'
    
])  #;removing irrelevant columns

In [73]:
df['date'] = pd.to_datetime(df['date']) #changing date column datatype to date

In [74]:
df['city'] = df['city'].fillna(df['venue']) #handling missing values of city column

In [75]:
df['target_runs'] = df['target_runs'].fillna(0)
df['target_overs'] = df['target_overs'].fillna(0)  #handling missing values of target runs and over column

In [76]:
df['player_of_match'] = df['player_of_match'].fillna("Unknown") #handling missing values of player of the match column

In [77]:
df['result_margin'] = df['result_margin'].fillna(0)  #handling missing values of result margin column

In [78]:
df = df.dropna(subset=['winner']) #removing missing values of winner column

In [79]:
df.isna().sum()

city               0
date               0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
dtype: int64

In [80]:
team_map = {
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiants' : 'Rising Pune Supergiant'
}

for col in ['team1', 'team2', 'winner', 'toss_winner']:
    df[col] = df[col].replace(team_map)

In [81]:
df['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Daredevils',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Lucknow Super Giants',
       'Gujarat Titans'], dtype=object)

In [82]:
df['target_runs'] = df['target_runs'].astype(int)
df['target_overs'] = df['target_overs'].astype(int)
df['result_margin'] = df['result_margin'].astype(int) #changing datatype of this columns to integer

In [83]:
df.dtypes

city                       object
date               datetime64[ns]
player_of_match            object
venue                      object
team1                      object
team2                      object
toss_winner                object
toss_decision              object
winner                     object
result                     object
result_margin               int64
target_runs                 int64
target_overs                int64
dtype: object

In [84]:
df['team1'].nunique()

16

In [85]:
df['team2'].nunique()

16

In [86]:
df['toss_decision'].nunique()

2

In [87]:
df['venue'].nunique()

58

In [88]:
df['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Daredevils',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Lucknow Super Giants',
       'Gujarat Titans'], dtype=object)

In [89]:
df['target_runs'].describe()

count    1090.000000
mean      165.757798
std        33.305775
min        43.000000
25%       146.000000
50%       166.000000
75%       187.000000
max       288.000000
Name: target_runs, dtype: float64

In [90]:
df['result_margin'].describe()

count    1090.000000
mean       17.037615
std        21.734086
min         0.000000
25%         5.000000
50%         8.000000
75%        19.750000
max       146.000000
Name: result_margin, dtype: float64

In [91]:
df['target_overs'].describe()

count    1090.000000
mean       19.772477
std         1.519259
min         5.000000
25%        20.000000
50%        20.000000
75%        20.000000
max        20.000000
Name: target_overs, dtype: float64

In [92]:
df = df.reset_index(drop=True) #index resting after rows deletion

In [93]:
df.to_csv("cleaned_matches.csv", index=False)

In [94]:
new = pd.read_csv('cleaned_matches.csv')
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1090 entries, 0 to 1089
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   city             1090 non-null   object
 1   date             1090 non-null   object
 2   player_of_match  1090 non-null   object
 3   venue            1090 non-null   object
 4   team1            1090 non-null   object
 5   team2            1090 non-null   object
 6   toss_winner      1090 non-null   object
 7   toss_decision    1090 non-null   object
 8   winner           1090 non-null   object
 9   result           1090 non-null   object
 10  result_margin    1090 non-null   int64
 11  target_runs      1090 non-null   int64
 12  target_overs     1090 non-null   int64
dtypes: int64(3), object(10)
memory usage: 110.8+ KB